# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 14:00
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosk_mdtools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdextension',
            name='resource',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.ResourceBase'),
        ),
    ]
